nav geo update
gdsclpu/wow-24 pull request #15
Opened 2024-03-20 20:21 UTC by sam-shubham

2024-03-20 21:03 UTC, Ba3a-G submitted a review, later dismissed
lgtm

2024-03-20 21:12 UTC, Ba3a-G requested changes
@sam-shubham fix the style
![image](https://github.com/gdsclpu/wow-24/assets/52352294/05794b81-b535-4b26-b823-28eaf39ca247)

2024-03-20 21:14 UTC, sam-shubham commented
> @sam-shubham fix the style ![image](https://private-user-images.githubusercontent.com/52352294/314676733-05794b81-b535-4b26-b823-28eaf39ca247.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5Njk1MTUsIm5iZiI6MTcxMDk2OTIxNSwicGF0aCI6Ii81MjM1MjI5NC8zMTQ2NzY3MzMtMDU3OTRiODEtYjUzNS00YjI2LWI4MjMtMjhlYWYzOWNhMjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDIxMTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ODM4YjA3NWFhNTJlMGQyYmU5MjBiOGM2YThlNjdlOGQyYmI5OGVmOTUzMWU0ODM2ZjQxNDJhNjc4YWU5ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s99dxZnrlzqlWLqJKfjOaGItz2ijcS4HAj9K4DJZq8k)

okay

2024-03-21 01:17 UTC, sam-shubham commented
Fixed That Styling and also making PR for HERO section

2024-03-21 01:17 UTC, closed without merging